todoListApp feedback
Ambrosegithub/todoListApp-feedBack pull request #1
Opened 2022-07-19 11:29 UTC by Ambrosegithub

###  create a todo-list-app to add, remove and update tasks

2022-07-21 17:03 UTC, looh16 requested changes
**Great Job!** 💪. 
There are some changes that need to be made.

2022-07-21 17:03 UTC, looh16 commented on src/modules/UserInterface.js
> +*/
I suggest you delete this file. It is not being used which makes your code not very clean.

2022-07-21 17:03 UTC, looh16 commented on src/modules/app.test.js
> +});
I suggest you change the context of this test. The correct context would be testing the tasks to be done and not calculations. This will help to make your code cleaner and more objective.

2022-07-22 07:48 UTC, looh16 approved these changes
Great Job! 🥳  Congratulations!! There's nothing more to say. Your project is approved.

2022-07-22 07:54 UTC, merged

2022-07-22 07:58 UTC, Ambrosegithub commented
Thank you